//
// Created by kimiko on 29.12.19.
//

#include "boards.h"

const char BOARD_1[SIZE][SIZE] = {
        {CARR,  CARR,  CARR,  CARR,  CARR,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 1
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 2
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, DEST,  EMPTY}, // 3
        {EMPTY, EMPTY, SUBM,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 4
        {CRUI,  EMPTY, SUBM,  EMPTY, EMPTY, SUBM,  EMPTY, EMPTY, EMPTY, EMPTY}, // 5
        {CRUI,  EMPTY, EMPTY, EMPTY, EMPTY, SUBM,  EMPTY, EMPTY, BATT,  EMPTY}, // 6
        {CRUI,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, BATT,  EMPTY}, // 7
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, BATT,  EMPTY}, // 8
        {EMPTY, DEST,  EMPTY, EMPTY, CRUI,  CRUI,  CRUI,  EMPTY, BATT,  EMPTY}, // 9
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}  // 10
};


const char BOARD_2[SIZE][SIZE] = {
        {DEST,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 1
        {EMPTY, EMPTY, EMPTY, SUBM,  EMPTY, EMPTY, EMPTY, EMPTY, CRUI,  EMPTY}, // 2
        {EMPTY, SUBM,  EMPTY, SUBM,  EMPTY, EMPTY, EMPTY, EMPTY, CRUI,  EMPTY}, // 3
        {EMPTY, SUBM,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, CRUI,  EMPTY}, // 4
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 5
        {EMPTY, EMPTY, EMPTY, CARR,  CARR,  CARR,  CARR,  CARR,  EMPTY, EMPTY}, // 6
        {EMPTY, CRUI,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, DEST},  // 7
        {EMPTY, CRUI,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 8
        {EMPTY, CRUI,  EMPTY, EMPTY, BATT,  BATT,  BATT,  BATT,  EMPTY, EMPTY}, // 9
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}  // 10
};

const char BOARD_3[SIZE][SIZE] = {
        {BATT,  EMPTY, EMPTY, EMPTY, SUBM,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 1
        {BATT,  EMPTY, EMPTY, EMPTY, SUBM,  EMPTY, EMPTY, EMPTY, CARR,  EMPTY}, // 2
        {BATT,  EMPTY, DEST,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, CARR,  EMPTY}, // 3
        {BATT,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, CARR,  EMPTY}, // 4
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, CARR,  EMPTY}, // 5
        {EMPTY, EMPTY, EMPTY, EMPTY, CRUI,  CRUI,  CRUI,  EMPTY, CARR,  EMPTY}, // 6
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 7
        {DEST,  EMPTY, CRUI,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 8
        {EMPTY, EMPTY, CRUI,  EMPTY, EMPTY, EMPTY, SUBM,  SUBM,  EMPTY, EMPTY}, // 9
        {EMPTY, EMPTY, CRUI,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}  // 10
};

const char BOARD_4[SIZE][SIZE] = {
        {EMPTY, EMPTY,  EMPTY, DEST,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 1
        {EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, EMPTY, BATT,  BATT,  BATT,  BATT},  // 2
        {EMPTY, SUBM,   SUBM,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 3
        {EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 4
        {EMPTY, EMPTY,  EMPTY, CRUI,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 5
        {EMPTY, CARR,   EMPTY, CRUI,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 6
        {EMPTY, CARR,   EMPTY, CRUI,  EMPTY, DEST,  EMPTY, EMPTY, EMPTY, EMPTY}, // 7
        {EMPTY, CARR,   EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, SUBM,  EMPTY}, // 8
        {EMPTY, CARR,   EMPTY, CRUI,  CRUI,  CRUI,  EMPTY, EMPTY, SUBM,  EMPTY}, // 9
        {EMPTY, CARR,   EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}  // 10
};

const char BOARD_5[SIZE][SIZE] = {
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, BATT,  BATT,  BATT,  BATT,  EMPTY}, // 1
        {EMPTY, CRUI,  CRUI,  CRUI,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, SUBM}, // 2
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, CRUI,  EMPTY, SUBM}, // 3
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, CRUI,  EMPTY, EMPTY}, // 4
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, CRUI,  EMPTY, EMPTY}, // 5
        {CARR,  CARR,  CARR,  CARR,  CARR,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 6
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 7
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, SUBM,  EMPTY}, // 8
        {EMPTY, DEST,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, SUBM,  EMPTY}, // 9
        {EMPTY, EMPTY, EMPTY, DEST,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}  // 10
};

const char EMPTY_BOARD[SIZE][SIZE] = {
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 1
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 2
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 3
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 4
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 5
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 6
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 7
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 8
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 9
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}  // 10
};

const char TUTORIAL_BOARD[SIZE][SIZE] = {
        {CARR,  CARR,  CARR,  CARR,  CARR,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 1
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 2
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 3
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 4
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 5
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 6
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 7
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 8
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}, // 9
        {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY}  // 10
};

const char NOT_TESTED_BOARD[SIZE][SIZE] = {
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 1
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 2
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 3
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 4
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 5
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 6
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 7
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 8
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 9
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}  // 10
};

const char TUTORIAL_BOARD_2[SIZE][SIZE] = {
        {HIT,        NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 1
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 2
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 3
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 4
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 5
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 6
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 7
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 8
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}, // 9
        {NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED, NOT_TESTED}  // 10
};